databases:
  - name: "Question Queue"
    user: "Question Queue"
    plan: free
    region: ohio

services:
  - type: web
    name: "Question Queue"
    plan: free
    region: ohio
    branch: main
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: "Question Queue"
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
